<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/common.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/status.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/product-backlog.css" />
<div class="product-backlog">
<?php
	echo $this->partialLoop()
			  ->setObjectKey( 'story' )
			  ->partialLoop( 'story/partials/partial-story.phtml', $this->stories );

?>
</div>