<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/common.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/status.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/product-backlog.css" />
<?php
	echo $this->partialLoop()
			  ->setObjectKey( 'product' )
			  ->partialLoop( 'product/partials/partial-product-minimized.phtml', $this->products );
?>