<link rel="stylesheet" type="text/css" media="screen" href="/css/sprint.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/table.css" />
<script src="/js/sprint.js"></script>
<h2>Sprint 3 : début le 15/03, fin le 29/03</h2>
<h3>But : Lorem ipsum</h3>
<table>
	<thead>
		<tr>
			<th class="top-left" style="width : 22%;">&nbsp;</th>
			<th class="top-center" style="width : 22%;">À FAIRE</th>
			<th class="top-center" style="width : 22%;">EN COURS</th>
			<th class="top-right" style="width : 22%;">FINI</th>
		</tr>
	</thead>
	<tbody>
		<tr class="storiesList" id="story_1">
			<td class="center-left" style="width : 22%;">
				<div class="story" style="border-color : #CCC;">
					<span class="item">Gestion des sprints</span>
				</div>
			</td>
			<td class="droppable center-center" style="width : 22%;" id="story_1_1">
				<div class="draggable" id="story_1_1_1">
					<span class="item">Créer sprint</span>
				</div>
				<div class="draggable" id="story_1_1_2">
					<span class="count">3</span>
					<span class="item">Modifier sprint</span>
				</div>
				<div class="draggable" id="story_1_1_3">
					<span class="count">4</span>
					<span class="item">supprimer sprint</span>
				</div>
			</td>
			<td class="droppable center-center" style="width : 22%;" id="story_1_2">
				<div class="draggable" id="story_1_2_1">
					<span class="count">2</span>
					<span class="item">Afficher sprints</span>
				</div>
			</td>
			<td class="droppable center-right" style="width : 22%;" id="story_1_3">&nbsp;
			</td>
		</tr>
		<tr class="storiesList" id="story_2">
			<td class="center-left" style="width : 15%;">
				<div class="story" style="border-color : #B3CA00;" >Gestion des tasks</div>
			</td>
			<td class="center-center" style="width : 15%;" id="story_2_1">
				<div class="draggable" id="2_1_1">
					<span class="count">1</span>
					<span class="item">créer tasks</span>
				</div>
				<div class="draggable" id="2_1_2">
					<span class="count">2</span>
					<span class="item">afficher tasks</span>
				</div>
				<div class="draggable" id="2_1_3">
					<span class="count">3</span>
					<span class="item">modifier tasks</span>
				</div>
				<div class="draggable" id="2_1_4">
					<span class="count">3</span>
					<span class="item">supprimer tasks</span>
				</div>
			</td>
			<td class="center-center" style="width : 15%;" id="story_2_2">&nbsp;</td>
			<td class="center-right" style="width : 15%;" id="story_2_3">&nbsp;</td>
		</tr>
		<tr class="storiesList" id="story_3">
			<td class="bottom-left" style="width : 15%;">
				<div class="story" style="border-color : #8EF5D9;">Gestion des releases</div>
			</td>
			<td class="bottom-center" style="width : 15%;" id="story_3_1">&nbsp;</td>
			<td class="bottom-center" style="width : 15%;" id="story_3_2">&nbsp;</td>
			<td class="bottom-right" style="width : 15%;" id="story_3_3">
				<div class="draggable" id="3_3_1">
					<span class="count">2</span>
					<span class="item">a</span>
				</div>
				<div class="draggable" id="3_3_2">
					<span class="count">3</span>
					<span class="item">b</span>
				</div>
			</td>
		</tr>
	</tbody>
</table>