<link rel="stylesheet" type="text/css" media="screen" href="/css/sprint.css" />
<link rel="stylesheet" type="text/css" media="screen" href="/css/table.css" />
<script src="/js/jquery.js"></script>
<script src="/js/jquery.ui.custom.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.mouse.js"></script>
<script src="/js/jquery.ui.draggable.js"></script>
<script src="/js/jquery.ui.droppable.js"></script>
<script src="/js/jquery.ui.sortable.js"></script>
<script src="/js/sprint.js"></script>
<h2>Sprint 3 : début le 15/03, fin le 29/03</h2>
<h3>But : Lorem ipsum</h3>
<div>
	<div class="top-left" style="width : 22%; float : left;">&nbsp;</div>
	<div class="top-center" style="width : 22%; float : left;">À FAIRE</div>
	<div class="top-center" style="width : 22%; float : left;">EN COURS</div>
	<div class="top-right" style="width : 22%; float : left;">FINI</div>
</div>
<div class="spacer">&nbsp;</div>
<div class="storiesList" id="story_1">
	<div class="center-left" style="width : 22%; float : left;">
		<div class="story" style="border-color : #CCC;">Story 1</div>
	</div>
	<div class="droppable center-center" style="width : 22%; float : left;" id="story_1_1">
		<div class="draggable" id="story_1_1_1">
			<span class="count">1</span>
			<span class="item">a</span>
		</div>
	</div>
	<div class="droppable center-center" style="width : 22%; float : left;" id="story_1_2">
		<div class="draggable" id="story_1_2_1">
			<span class="count">2</span>
			<span class="item">b</span>
		</div>
	</div>
	<div class="droppable center-right" style="width : 22%; float : left;" id="story_1_3">
		<div class="draggable" id="story_1_3_1">
			<span class="count">3</span>
			<span class="item">c</span>
		</div>
		<div class="draggable" id="story_1_3_2">
			<span class="count">4</span>
			<span class="item">d</span>
		</div>
	</div>
</div>
<div class="spacer">&nbsp;</div>
<div class="storiesList">
	<div class="center-left" style="width : 15%; float : left;">
		<div class="story" style="border-color : #B3CA00;" >Story 2</div>
	</div>
	<div class="center-center" style="width : 15%; float : left;">
		<div class="draggable" id="2_1">
			<span class="count">1</span>
			<span class="item">a</span>
		</div>
	</div>
	<div class="center-center" style="width : 15%; float : left;">
		<div class="draggable" id="2_2">
			<span class="count">2</span>
			<span class="item">b</span>
		</div>
	</div>
	<div class="center-right" style="width : 15%; float : left;">
		<div class="draggable" id="2_3" >
			<span class="count">3</span>
			<span class="item">c</span>
		</div>
	</div>
</div>
<div class="spacer">&nbsp;</div>
<div class="storiesList">
	<div class="bottom-left" style="width : 15%; float : left;">
		<div class="story" style="border-color : #8EF5D9;">Story 3</div>
	</div>
	<div class="bottom-center" style="width : 15%; float : left;"></div>
	<div class="bottom-center" style="width : 15%; float : left;"></div>
	<div class="bottom-right" style="width : 15%; float : left;">
		<div class="draggable" id="3_1">
			<span class="count">2</span>
			<span class="item">a</span>
		</div>
		<div class="draggable" id="3_2">
			<span class="count">3</span>
			<span class="item">b</span>
		</div>
	</div>
</div>