<div class="divRelease">
	<a href="<?php echo $this->baseUrl();?>/release/edit/id/<?php echo  $this->escape( $this->release->getId() ); ?>">
		<img class="edit" src="<?php echo $this->baseUrl();?>/images/edit.png" alt="edit release" title="edit release" />
	</a>
	<h4>
		<a href="<?php echo $this->baseUrl();?>/release/display/id/<?php echo $this->release->getId(); ?>"><?php echo $this->release->getName();?></a>
	</h4>
	<div title="<?php echo $this->escape( $this->release->getStatus()->getName() ); ?>" class="status <?php echo $this->escape( $this->release->getStatus()->getName() ); ?>">
		<span class="startDate">
			<img src="<?php echo $this->baseUrl();?>/images/flag-start.png" />
			<?php echo $this->release->getStartDate(); ?>
		</span>
		<span class="endDate">
			<img src="<?php echo $this->baseUrl();?>/images/flag-end.png" />
			<?php echo $this->release->getEndDate(); ?>
		</span>
	</div>
</div>